"""安全的 Python 模块清单。

仅包含不涉及 I/O、网络、进程操作的纯计算库。
"""

DEFAULT_ALLOWED_MODULES: list[str] = [
    # 标准库（安全）
    "math",
    "cmath",
    "statistics",
    "random",
    "collections",
    "itertools",
    "functools",
    "operator",
    "copy",
    "pprint",
    "json",
    "csv",
    "re",
    "string",
    "textwrap",
    "datetime",
    "time",
    "typing",
    "dataclasses",
    "enum",
    "abc",
    "numbers",
    "decimal",
    "fractions",
    "hashlib",
    "bisect",
    "heapq",
    "array",
    "struct",
    "io",
    "base64",
    "binascii",
    "codecs",
    "unicodedata",
    "pathlib",
    "inspect",
    "dis",
    "ast",
    "tokenize",
    "types",
    "warnings",
    "contextlib",
    "typing_extensions",
    # 第三方库（数据分析，需安装）
    "pandas",
    "numpy",
    "scipy",
    "sklearn",
    "matplotlib",
    "seaborn",
    "plotly",
    "sympy",
    "networkx",
    "requests",  # HTTP 客户端，沙箱中可能被 network_disabled 禁止
]
